"""Encoder vectors generated by running the reference JS (evanw/thumbhash)."""

from __future__ import annotations

import base64
import math

import pytest

from gateway.adapters.thumbhash import rgba_to_thumbhash, thumbhash_to_average_rgba


def solid(width: int, height: int, rgba: tuple[int, int, int, int]) -> bytes:
    return bytes(rgba) * (width * height)


def gradient(width: int, height: int) -> bytes:
    pixels = bytearray()
    for y in range(height):
        for x in range(width):
            pixels += bytes(
                [
                    math.floor(255 * x / (width - 1) + 0.5),
                    math.floor(255 * y / (height - 1) + 0.5),
                    128,
                    255,
                ]
            )
    return bytes(pixels)


def alpha_fade(width: int, height: int) -> bytes:
    pixels = bytearray()
    for _y in range(height):
        for x in range(width):
            pixels += bytes([255, 0, 0, math.floor(255 * x / (width - 1) + 0.5)])
    return bytes(pixels)


def noise(width: int, height: int, with_alpha: bool) -> bytes:
    """ZX81 LCG noise; every channel varies, so no AC term sits at fp-noise level.

    Solid images make bad exact-match vectors: their AC scale is ~1e-17, and
    noise divided by a noise scale amplifies last-ulp libm differences between
    the JS reference and Python into different nibbles.
    """
    seed = 1
    pixels = bytearray()

    def nxt() -> int:
        nonlocal seed
        seed = (seed * 75 + 74) % 65537
        return seed & 255

    for _ in range(width * height):
        pixels += bytes([nxt(), nxt(), nxt(), nxt() if with_alpha else 255])
    return bytes(pixels)


VECTORS = [
    ("gradient_100x75", 100, 75, gradient(100, 75), "4PcJNZqAh4eAd3d3iHiHiICAB/iH"),
    ("gradient_75x100", 75, 100, gradient(75, 100), "4AcKNRpwh4CIiIh4iHh4eHBwCPd4"),
    ("noise_31x47", 31, 47, noise(31, 47, False), "HwgCDQKKiGdRWcbci3u88wpFTvdW"),
    ("noise_47x31", 47, 31, noise(47, 31, False), "HwgCDYK/RHtHiWm0ieZ53PiFnvpX"),
    (
        "alpha_noise_20x20",
        20,
        20,
        noise(20, 20, True),
        "3/eBDQIHrZiLn3u3Cchv9IZ3h3CNR4m4hg==",
    ),
]


@pytest.mark.parametrize(
    ("width", "height", "rgba", "expected"),
    [pytest.param(w, h, px, exp, id=name) for name, w, h, px, exp in VECTORS],
)
def test_encoder_matches_the_reference_implementation(
    width: int, height: int, rgba: bytes, expected: str
) -> None:
    assert base64.b64encode(rgba_to_thumbhash(width, height, rgba)).decode() == expected


def test_the_hash_is_compact() -> None:
    for _, width, height, rgba, _expected in VECTORS:
        assert len(rgba_to_thumbhash(width, height, rgba)) <= 25


def test_average_color_survives_the_round_trip() -> None:
    hash_bytes = rgba_to_thumbhash(8, 8, solid(8, 8, (255, 0, 0, 255)))

    r, g, b, a = thumbhash_to_average_rgba(hash_bytes)

    assert r == pytest.approx(1.0, abs=0.02)
    assert g == pytest.approx(0.0, abs=0.02)
    assert b == pytest.approx(0.0, abs=0.02)
    assert a == 1.0


def test_alpha_is_flagged_and_recovered() -> None:
    hash_bytes = rgba_to_thumbhash(32, 32, alpha_fade(32, 32))

    *_rgb, a = thumbhash_to_average_rgba(hash_bytes)

    assert a == pytest.approx(0.53, abs=0.05)


def test_oversized_input_is_rejected() -> None:
    with pytest.raises(ValueError, match="doesn't fit"):
        rgba_to_thumbhash(101, 1, bytes(101 * 4))


def test_wrong_buffer_length_is_rejected() -> None:
    with pytest.raises(ValueError, match="RGBA bytes"):
        rgba_to_thumbhash(2, 2, bytes(3))
