import { http, HttpResponse } from 'msw'
import { COLD_QUEUE_MS } from '../hooks/useBatch'
import type {
  ErrorBody,
  JobStatus,
  JobSummary,
  JobView,
  RequestEcho,
} from '../api/types'

/** Thumbhash of public/mock/sample.png, computed at mock-authoring time. */
const SAMPLE_THUMBHASH = 'necNFwJ0aYiAdniJd3imiWiHd7AGB1sA'
const MODEL_VERSION =
  'black-forest-labs/FLUX.1-dev@3de623fc3c33e44ffbe2bad470d0f45bccf2eb21'

function randomHex(bytes: number): string {
  const buf = new Uint8Array(bytes)
  crypto.getRandomValues(buf)
  return [...buf].map((b) => b.toString(16).padStart(2, '0')).join('')
}

/** Fresh per response, like the gateway's per-request middleware. */
function correlationId(): string {
  return randomHex(16)
}

function withHeaders(extra?: Record<string, string>): Record<string, string> {
  return { 'X-Correlation-ID': correlationId(), ...extra }
}

function errorJson(
  status: number,
  code: string,
  message: string,
  suggestion?: string,
  headers?: Record<string, string>,
) {
  return HttpResponse.json(
    {
      error: {
        code,
        message,
        suggestion: suggestion ?? null,
        correlation_id: correlationId(),
      },
    },
    { status, headers: withHeaders(headers) },
  )
}

type Scenario = 'ok' | 'blocked' | 'oom' | 'cold' | 'hold' | 'mixed'

/**
 * Scenario tokens require the demo: prefix ("demo:oom") so plain prompts
 * containing words like "cold" or "blocked" behave normally. A prompt may
 * carry several ("demo:shed-one demo:mixed").
 */
function demoTokens(prompt: string): string[] {
  return [...prompt.matchAll(/demo:([a-z-]+)/g)].map((m) => m[1])
}

/**
 * Idempotency-Key → job id for every create that reached the job store. A
 * reused key replays the stored job as a 200 JobView instead of creating a
 * duplicate — the contract the client's retry-after-429/network-drop relies on.
 */
const idempotencyKeys = new Map<string, string>()

/** 'demo:drop-first' keys whose create succeeded but whose response was "lost". */
const droppedKeys = new Set<string>()

/** 'demo:shed' keys already 429ed once — the first retry succeeds. */
const shedKeys = new Set<string>()

/**
 * Submissions within 3s of each other form a "burst" (a client batch). The
 * index within the burst drives deterministic per-cell timing offsets so
 * batch cells visibly finish at different moments.
 */
let burstLastMs = 0
let burstNext = 0
let burstFirstSeed: number | null | undefined
function nextBurstIndex(now: number): number {
  if (now - burstLastMs > 3000) burstNext = 0
  burstLastMs = now
  return burstNext++
}

/**
 * 'demo:shed-one' 429s exactly one submission — the first in a 60s window — so
 * a batch loses one cell and that cell's retry (after Retry-After) succeeds.
 */
let shedOneLastMs = 0

function burstOffsetMs(job: MockJob): number {
  if (job.scenario !== 'ok') return 0
  // sweep bursts (same locked seed per cell) get no stagger: per-cell wall
  // differences must come from the varied parameter alone
  if (job.sameSeedBurst) return 0
  return job.burst * (fast() ? 700 : 1500)
}

/**
 * Inference-time scale vs the 28-steps/1024² baseline, per BENCHMARKS.md:
 * steps are linear, size scales with pixel count, guidance has no time cost —
 * that is the lesson a guidance sweep teaches.
 */
function inferenceScale(job: MockJob): number {
  return (job.steps / 28) * ((job.width * job.height) / (1024 * 1024))
}

/** Per-poll progress stride; also the source of truth for inference_seconds. */
function strideMsOf(job: MockJob): number {
  const { strideMs: baseStrideMs } = timing(job.scenario)
  return Math.max(20, baseStrideMs * inferenceScale(job))
}

/**
 * Reported inference time = the 11 strides the mock actually spends denoising,
 * floored to 0.1s — so inference_seconds ≤ observed wall in every mode.
 */
function inferenceSeconds(job: MockJob): number {
  return Math.floor((11 * strideMsOf(job)) / 100) / 10
}

/**
 * Denoising previews generated by scripts/make-preview-frames.mjs from
 * sample.png. Served as progress.preview_b64 on mid-run polls (≥30%).
 */
let previewFrames: string[] = []
let previewLoad: Promise<void> | null = null

function toBase64(buf: ArrayBuffer): string {
  const bytes = new Uint8Array(buf)
  let bin = ''
  for (let i = 0; i < bytes.length; i += 0x8000) {
    bin += String.fromCharCode(...bytes.subarray(i, i + 0x8000))
  }
  return btoa(bin)
}

function ensurePreviewFrames(): Promise<void> {
  previewLoad ??= Promise.all(
    [1, 2, 3, 4].map(async (n) => {
      const res = await fetch(`/mock/preview-${n}.jpg`)
      return toBase64(await res.arrayBuffer())
    }),
  )
    .then((frames) => {
      previewFrames = frames
    })
    .catch(() => {
      // frames missing: progress polls simply carry no preview
    })
  return previewLoad
}

function previewAt(percent: number): { preview_b64: string; preview_format: 'jpeg' } | null {
  const idx =
    percent >= 100 ? null
    : percent >= 90 ? 3
    : percent >= 70 ? 2
    : percent >= 50 ? 1
    : percent >= 30 ? 0
    : null
  const b64 = idx === null ? undefined : previewFrames[idx]
  return b64 ? { preview_b64: b64, preview_format: 'jpeg' } : null
}

interface MockJob {
  id: string
  prompt: string
  width: number
  height: number
  steps: number
  guidance: number
  seed: number | null
  format: 'png' | 'jpeg'
  createdAtMs: number
  scenario: Scenario
  cancelledAtMs: number | null
  /** the job's correlation id: minted at create, stable across polls */
  corr: string
  /** index within a burst of near-simultaneous submissions */
  burst: number
  /** burst shares one seed = a sweep; timing stagger is disabled */
  sameSeedBurst: boolean
}

const jobs = new Map<string, MockJob>()

function fast(): boolean {
  return localStorage.getItem('MOCK_FAST') === '1'
}

/**
 * 'demo:cold' has to out-queue COLD_QUEUE_MS or the completed card shows no
 * cold split — derived from the threshold so the two cannot drift. Fast mode
 * pays the full ~22.5s here; every other scenario stays sub-second.
 */
function coldQueuedMs(isFast: boolean): number {
  return isFast ? COLD_QUEUE_MS + 2500 : Math.max(45_000, COLD_QUEUE_MS + 2500)
}

function timing(scenario: Scenario) {
  // demo pacing: ~1 stride per poll so every preview frame is observed on video
  if (localStorage.getItem('MOCK_DEMO') === '1') {
    return { queuedMs: 1500, strideMs: 900 }
  }
  const isFast = fast()
  return {
    queuedMs:
      scenario === 'cold' ? coldQueuedMs(isFast) : isFast ? 600 : 2000,
    strideMs: isFast ? 300 : 200,
  }
}

/** demo:mixed settle points: burst 1 OOMs, burst 2+ times out. */
function mixedDeadlines() {
  return fast() ? { oomMs: 14_000, timeoutMs: 22_000 } : { oomMs: 30_000, timeoutMs: 45_000 }
}

function errorBody(
  job: MockJob,
  code: string,
  message: string,
  suggestion: string,
): ErrorBody {
  return { code, message, suggestion, correlation_id: job.corr }
}

function oomError(job: MockJob): ErrorBody {
  return errorBody(
    job,
    'OOM',
    `CUDA out of memory while denoising at ${job.width}×${job.height}, ${job.steps} steps.`,
    'Reduce the resolution or step count and retry.',
  )
}

function requestEcho(job: MockJob): RequestEcho {
  return {
    prompt: job.prompt,
    width: job.width,
    height: job.height,
    num_inference_steps: job.steps,
    guidance_scale: job.guidance,
    output_format: job.format,
    ...(job.seed !== null ? { seed: job.seed } : {}),
  }
}

function viewOf(job: MockJob): JobView {
  const { queuedMs } = timing(job.scenario)
  // param-dependent pacing: total mock inference time tracks the benchmarks
  const strideMs = strideMsOf(job)
  const now = Date.now()
  const t = now - job.createdAtMs - burstOffsetMs(job)
  const iso = (ms: number) => new Date(ms).toISOString()

  const base = {
    job_id: job.id,
    request: requestEcho(job),
    created_at: iso(job.createdAtMs),
    updated_at: iso(now),
  }
  const seed = job.seed ?? 424242

  if (job.cancelledAtMs !== null) {
    return {
      ...base,
      status: 'CANCELLED',
      progress: null,
      result: null,
      error: errorBody(
        job,
        'JOB_CANCELLED',
        'The job was cancelled by the caller.',
        'Submit again to rerun it.',
      ),
      completed_at: iso(job.cancelledAtMs),
    }
  }

  if (job.scenario === 'blocked') {
    if (t < 400) {
      return { ...base, status: 'QUEUED', progress: null, result: null, error: null, completed_at: null }
    }
    return {
      ...base,
      status: 'BLOCKED',
      progress: null,
      result: null,
      error: errorBody(
        job,
        'PROMPT_BLOCKED',
        'The prompt matched the content blocklist.',
        'Rephrase the prompt and resubmit.',
      ),
      completed_at: iso(job.createdAtMs + 400),
    }
  }

  // mixed batch scenario, deterministic per burst index:
  // 0 → completes normally, 1 → previews then OOMs, 2+ → queued then times out
  if (job.scenario === 'mixed' && job.burst >= 2) {
    const { timeoutMs } = mixedDeadlines()
    if (t < timeoutMs) {
      return { ...base, status: 'QUEUED', progress: null, result: null, error: null, completed_at: null }
    }
    return {
      ...base,
      status: 'TIMED_OUT',
      progress: null,
      result: null,
      error: errorBody(
        job,
        'TIMED_OUT',
        'No worker picked the job up before the queue deadline.',
        'Resubmit; a warm worker usually starts within a second.',
      ),
      completed_at: iso(job.createdAtMs + timeoutMs),
    }
  }

  if (t < queuedMs) {
    return { ...base, status: 'QUEUED', progress: null, result: null, error: null, completed_at: null }
  }

  // deterministic mid-denoise state for visual baselines: parks at 60%
  // (forever for demo:hold; until the OOM deadline for the mixed cell)
  if (job.scenario === 'hold' || (job.scenario === 'mixed' && job.burst === 1)) {
    const { oomMs } = mixedDeadlines()
    if (job.scenario === 'mixed' && t >= oomMs) {
      return {
        ...base,
        status: 'FAILED',
        progress: { step: Math.round(0.6 * job.steps), total: job.steps, percent: 60 },
        result: null,
        error: oomError(job),
        completed_at: iso(job.createdAtMs + oomMs),
      }
    }
    return {
      ...base,
      status: 'IN_PROGRESS',
      progress: {
        step: Math.round(0.6 * job.steps),
        total: job.steps,
        percent: 60,
        ...(previewAt(60) ?? {}),
      },
      result: null,
      error: null,
      completed_at: null,
    }
  }

  const stride = Math.floor((t - queuedMs) / strideMs)
  const percent = Math.min(100, stride * 10)

  if (job.scenario === 'oom' && percent >= 40) {
    return {
      ...base,
      status: 'FAILED',
      progress: { step: Math.round((40 / 100) * job.steps), total: job.steps, percent: 40 },
      result: null,
      error: oomError(job),
      completed_at: iso(job.createdAtMs + queuedMs + 4 * strideMs),
    }
  }

  // one stride at 100% before COMPLETED, so the finalize transition is observable
  if (percent >= 100 && stride >= 11) {
    return {
      ...base,
      status: 'COMPLETED',
      progress: { step: job.steps, total: job.steps, percent: 100 },
      result: {
        image_url: `/v1/jobs/${job.id}/image`,
        thumbhash: SAMPLE_THUMBHASH,
        format: job.format,
        seed,
        width: job.width,
        height: job.height,
        model_version: MODEL_VERSION,
        inference_seconds: inferenceSeconds(job),
      },
      error: null,
      completed_at: iso(job.createdAtMs + burstOffsetMs(job) + queuedMs + 11 * strideMs),
    }
  }

  return {
    ...base,
    status: 'IN_PROGRESS',
    progress: {
      step: Math.round((percent / 100) * job.steps),
      total: job.steps,
      percent,
      ...(previewAt(percent) ?? {}),
    },
    result: null,
    error: null,
    completed_at: null,
  }
}

interface GallerySpec {
  id: string
  day: string
  time: string
  prompt: string
  width: number
  height: number
  steps?: number
  guidance?: number
  seed: number
  inference: number
  status?: JobStatus
  errorCode?: string
}

/** Fixed realistic job ids — deterministic for baselines, no zero runs. */
const GALLERY_SPECS: GallerySpec[] = [
  { id: '7f3a91c4-88e2-4d17-9b60-4be1f0d2a6ce', day: '2026-08-09', time: '09:41:02', prompt: 'a red fox in falling snow, cinematic lighting', width: 1024, height: 1024, seed: 42, inference: 21.4 },
  { id: 'c09be1d5-6f2a-4b93-8a41-72cf90e3b18d', day: '2026-08-09', time: '09:22:47', prompt: 'lighthouse on a basalt cliff, long exposure', width: 1024, height: 1024, guidance: 7, seed: 7, inference: 21.9 },
  { id: '3e5d20fb-9c74-4a68-b1d9-e60a8f14c772', day: '2026-08-09', time: '08:58:13', prompt: 'great horned owl, studio portrait, rim light', width: 768, height: 768, seed: 1234, inference: 12.7 },
  { id: 'ab47d8e0-1c39-4f56-92b7-08d4e6a95f31', day: '2026-08-09', time: '08:31:55', prompt: 'antarctic research station at dusk, film grain', width: 1280, height: 1280, seed: 90210, inference: 36.2, status: 'FAILED', errorCode: 'OOM' },
  { id: '5d82c6f9-e4b0-4721-a3c8-96f1d20b7e45', day: '2026-08-08', time: '17:12:30', prompt: 'brutalist library interior, fog, volumetric light', width: 1024, height: 1024, seed: 42, inference: 22.0 },
  { id: 'e91f4ab2-07d6-4c85-b592-3ac0f78e61d9', day: '2026-08-08', time: '16:44:08', prompt: 'macro shot of a circuit board river delta', width: 512, height: 768, steps: 20, seed: 555, inference: 8.1 },
  { id: '28c7e3d1-b5f9-4a04-8e67-d92b1c50fa83', day: '2026-08-08', time: '16:03:29', prompt: 'paper crane armada over a paper sea', width: 1024, height: 1024, seed: 31337, inference: 21.6 },
  { id: 'f60b92a8-3d41-4c7e-95f0-1e8ad6c42b97', day: '2026-08-08', time: '15:40:11', prompt: 'terraced tea fields, drone view, morning mist', width: 1536, height: 1024, seed: 2718, inference: 41.0 },
  { id: '94d1f7c3-a82e-4b60-87d5-c30e9f16a248', day: '2026-08-06', time: '12:19:44', prompt: 'a locomotive made of glass, golden hour', width: 1024, height: 1024, seed: 16180, inference: 21.5 },
  { id: '6ba0d549-f217-4e83-9c26-58e7b3a1d0f4', day: '2026-08-06', time: '11:52:02', prompt: 'deep sea anglerfish, bioluminescent, ink wash', width: 768, height: 1024, seed: 999, inference: 15.3 },
  { id: 'd35c8ef7-42a9-4b18-a6e0-79c2d81f5b36', day: '2026-08-06', time: '11:30:56', prompt: 'city block rendered as an exploded diagram', width: 1024, height: 1024, seed: 8080, inference: 21.7, status: 'BLOCKED', errorCode: 'PROMPT_BLOCKED' },
  { id: '17e9a2b6-c50d-4f74-b8a3-e64f01d92c85', day: '2026-08-06', time: '10:58:19', prompt: 'salt flats after rain, perfect mirror, cyclist', width: 1024, height: 768, seed: 60, inference: 17.8 },
]

function staticSummaries(): JobSummary[] {
  return GALLERY_SPECS.map((spec) => {
    const failed = spec.status !== undefined
    const created = `${spec.day}T${spec.time}Z`
    const completed = new Date(
      new Date(created).getTime() + Math.round(spec.inference * 1000) + 1600,
    ).toISOString()
    return {
      job_id: spec.id,
      status: spec.status ?? 'COMPLETED',
      prompt: spec.prompt,
      width: spec.width,
      height: spec.height,
      num_inference_steps: spec.steps ?? 28,
      guidance_scale: spec.guidance ?? 3.5,
      output_format: 'png' as const,
      seed: spec.seed,
      thumbhash: failed ? null : SAMPLE_THUMBHASH,
      image_url: failed ? null : `/v1/jobs/${spec.id}/image`,
      model_version: failed ? null : MODEL_VERSION,
      inference_seconds: failed ? null : spec.inference,
      error_code: spec.errorCode ?? null,
      created_at: created,
      completed_at: failed && spec.status === 'BLOCKED' ? created : completed,
    }
  })
}

/** Stable per-job correlation ids for the static ledger: derived, not zeroed. */
function staticCorr(jobId: string): string {
  return jobId.replaceAll('-', '')
}

function staticView(summary: JobSummary): JobView {
  const completed = summary.status === 'COMPLETED'
  return {
    job_id: summary.job_id,
    status: summary.status,
    request: {
      prompt: summary.prompt,
      width: summary.width,
      height: summary.height,
      num_inference_steps: summary.num_inference_steps,
      guidance_scale: summary.guidance_scale,
      output_format: summary.output_format,
      ...(summary.seed !== null ? { seed: summary.seed } : {}),
    },
    progress: completed
      ? { step: summary.num_inference_steps, total: summary.num_inference_steps, percent: 100 }
      : null,
    result: completed
      ? {
          image_url: summary.image_url!,
          thumbhash: SAMPLE_THUMBHASH,
          format: summary.output_format,
          seed: summary.seed!,
          width: summary.width,
          height: summary.height,
          model_version: MODEL_VERSION,
          inference_seconds: summary.inference_seconds!,
        }
      : null,
    error:
      summary.error_code === 'OOM'
        ? {
            code: 'OOM',
            message: `CUDA out of memory while denoising at ${summary.width}×${summary.height}, ${summary.num_inference_steps} steps.`,
            suggestion: 'Reduce the resolution or step count and retry.',
            correlation_id: staticCorr(summary.job_id),
          }
        : summary.error_code === 'PROMPT_BLOCKED'
          ? {
              code: 'PROMPT_BLOCKED',
              message: 'The prompt matched the content blocklist.',
              suggestion: 'Rephrase the prompt and resubmit.',
              correlation_id: staticCorr(summary.job_id),
            }
          : null,
    created_at: summary.created_at,
    updated_at: summary.completed_at ?? summary.created_at,
    completed_at: summary.completed_at,
  }
}

/** BENCHMARKS.md's measured 48GB-tier rate — the gateway's own default. */
const GPU_RATE_USD_HR = 1.75
/** GATEWAY_METRICS_WINDOW default. */
const METRICS_WINDOW = 100
/** HEALTH_MAX_AGE_S default — the cutoff load shedding uses, so the queue reuses it. */
const QUEUE_STALE_AFTER_S = 30
/** Three RECONCILE_IDLE_INTERVAL_S (default 10s), the gateway's own derivation. */
const RECONCILER_STALE_AFTER_S = 30

const ALL_STATUSES: JobStatus[] = [
  'QUEUED',
  'IN_PROGRESS',
  'COMPLETED',
  'FAILED',
  'TIMED_OUT',
  'CANCELLED',
  'BLOCKED',
]

interface MetricRecord {
  status: JobStatus
  inferenceS: number | null
  createdMs: number
  completedMs: number | null
}

/**
 * Every job the mock knows, static ledger and live jobs alike — the same source
 * `/v1/jobs` answers from, so the dashboard can never contradict the ledger.
 */
function metricRecords(): MetricRecord[] {
  const fromStatic = staticSummaries().map((s): MetricRecord => ({
    status: s.status,
    inferenceS: s.inference_seconds,
    createdMs: new Date(s.created_at).getTime(),
    completedMs: s.completed_at ? new Date(s.completed_at).getTime() : null,
  }))
  const fromLive = [...jobs.values()].map((job): MetricRecord => {
    const view = viewOf(job)
    return {
      status: view.status,
      inferenceS: view.result?.inference_seconds ?? null,
      createdMs: new Date(view.created_at).getTime(),
      completedMs: view.completed_at ? new Date(view.completed_at).getTime() : null,
    }
  })
  return [...fromLive, ...fromStatic]
}

/** Nearest rank, the gateway's percentile definition. */
function percentile(sorted: number[], p: number): number | null {
  if (sorted.length === 0) return null
  return sorted[Math.min(sorted.length - 1, Math.ceil(p * sorted.length) - 1)]
}

function percentiles(values: number[]) {
  const sorted = [...values].sort((a, b) => a - b)
  return {
    p50_s: percentile(sorted, 0.5),
    p95_s: percentile(sorted, 0.95),
    max_s: sorted.length ? sorted[sorted.length - 1] : null,
  }
}

/**
 * The trailing hour the 24h window ends on. Live by default; 'MOCK_HOUR' pins it
 * so bar positions in the visual baselines do not drift with the wall clock.
 */
function windowEndHourMs(nowMs: number): number {
  const hourMs = 3_600_000
  const live = Math.floor(nowMs / hourMs) * hourMs
  const pinned = localStorage.getItem('MOCK_HOUR')
  if (pinned === null) return live
  return Math.floor(live / 86_400_000) * 86_400_000 + Number(pinned) * hourMs
}

/**
 * 24 dense buckets ending at the current UTC hour. The static ledger's days are
 * frozen so the visual baselines stay stable, so its completions are placed by
 * hour-of-day: every bar still counts real ledger jobs, and the sum equals the
 * completed jobs the ledger lists.
 */
function throughput(records: MetricRecord[], nowMs: number) {
  const hourMs = 3_600_000
  const currentHourMs = windowEndHourMs(nowMs)
  const startHourMs = currentHourMs - 23 * hourMs
  const startHourOfDay = new Date(startHourMs).getUTCHours()
  const counts = new Array<number>(24).fill(0)
  for (const record of records) {
    if (record.status !== 'COMPLETED' || record.completedMs === null) continue
    const hourOfDay = new Date(record.completedMs).getUTCHours()
    counts[(hourOfDay - startHourOfDay + 24) % 24] += 1
  }
  return counts.map((completed, i) => ({
    hour: new Date(startHourMs + i * hourMs).toISOString(),
    completed,
  }))
}

/** An empty store: what a fresh key sees before its first job. */
function emptyMetrics(nowMs: number) {
  return {
    jobs: {
      by_status: Object.fromEntries(ALL_STATUSES.map((s) => [s, 0])),
      last_hour: 0,
      active_now: 0,
    },
    latency: {
      inference: { p50_s: null, p95_s: null, max_s: null },
      wall: { p50_s: null, p95_s: null, max_s: null },
    },
    throughput: throughput([], nowMs),
    cost: {
      estimated_cost_usd: 0,
      estimated_cost_usd_per_job: null,
      exec_seconds_in_window: 0,
      gpu_rate_usd_hr: GPU_RATE_USD_HR,
    },
    upstream: {
      queue: {
        status: 'ok',
        in_queue: 0,
        in_progress: 0,
        workers_running: 0,
        workers_idle: 1,
        age_s: 4.2,
        stale: false,
        stale_after_s: QUEUE_STALE_AFTER_S,
      },
      reconciler: {
        status: 'ok',
        last_tick_s: 1.9,
        stale: false,
        stale_after_s: RECONCILER_STALE_AFTER_S,
      },
    },
    window: METRICS_WINDOW,
    completed_in_window: 0,
    window_started_at: null,
    window_ended_at: null,
    generated_at: new Date(nowMs).toISOString(),
  }
}

/**
 * The cached queue reading the mock reports, and the gateway's verdict on it.
 * `stale` follows the same rule the gateway applies — age past the threshold, or
 * no reading at all — except in 'old-trusted', which reports an old reading the
 * gateway still vouches for, so the dashboard is proven to obey the flag rather
 * than a cutoff of its own.
 */
function queueReading(mode: string | null, counts: {
  inQueue: number
  inProgress: number
  workersRunning: number
}) {
  if (mode === 'unknown') {
    return {
      status: 'unknown',
      in_queue: null,
      in_progress: null,
      workers_running: null,
      workers_idle: null,
      age_s: null,
      stale: true,
      stale_after_s: QUEUE_STALE_AFTER_S,
    }
  }
  const ageS = mode === 'stale' || mode === 'old-trusted' ? 47.3 : 4.2
  return {
    status: 'ok',
    in_queue: counts.inQueue,
    in_progress: counts.inProgress,
    workers_running: counts.workersRunning,
    workers_idle: 1 - counts.workersRunning,
    age_s: ageS,
    stale: mode === 'old-trusted' ? false : ageS > QUEUE_STALE_AFTER_S,
    stale_after_s: QUEUE_STALE_AFTER_S,
  }
}

function reconcilerReading(mode: string | null) {
  if (mode === 'unknown') {
    return {
      status: 'unknown',
      last_tick_s: null,
      stale: true,
      stale_after_s: RECONCILER_STALE_AFTER_S,
    }
  }
  const lastTickS = mode === 'stale' ? 96.4 : 1.9
  const stalled = lastTickS > RECONCILER_STALE_AFTER_S
  return {
    status: stalled ? 'stalled' : 'ok',
    last_tick_s: lastTickS,
    stale: stalled,
    stale_after_s: RECONCILER_STALE_AFTER_S,
  }
}

/**
 * MOCK_METRICS modes: 'empty' (a fresh key), 'stale' (queue and reconciler
 * readings past their thresholds), 'unknown' (no queue reading at all),
 * 'old-trusted' (an old reading the gateway still vouches for), 'single' (a
 * one-job window). Unset: the live store.
 */
function metricsSnapshot() {
  const nowMs = Date.now()
  const mode = localStorage.getItem('MOCK_METRICS')
  if (mode === 'empty') return emptyMetrics(nowMs)

  const records = metricRecords()
  const byStatus = Object.fromEntries(
    ALL_STATUSES.map((status) => [
      status,
      records.filter((r) => r.status === status).length,
    ]),
  )
  // 'single' is a gateway configured with GATEWAY_METRICS_WINDOW=1: one job in
  // the window, so its span collapses and no rate can be drawn from it
  const windowSize = mode === 'single' ? 1 : METRICS_WINDOW
  const window = records
    .filter((r) => r.status === 'COMPLETED' && r.completedMs !== null)
    .sort((a, b) => b.completedMs! - a.completedMs!)
    .slice(0, windowSize)
  const completedMs = window.map((r) => r.completedMs!)
  const inference = window
    .map((r) => r.inferenceS)
    .filter((v): v is number => v !== null)
  const wall = window.map((r) => (r.completedMs! - r.createdMs) / 1000)
  const execS = inference.reduce((sum, v) => sum + v, 0)
  const cost = (execS * GPU_RATE_USD_HR) / 3600
  const inQueue = records.filter((r) => r.status === 'QUEUED').length
  const inProgress = records.filter((r) => r.status === 'IN_PROGRESS').length
  // a fleet of one: the worker is running whenever it holds work
  const workersRunning = inProgress > 0 ? 1 : 0

  return {
    jobs: {
      by_status: byStatus,
      last_hour: records.filter((r) => nowMs - r.createdMs < 3_600_000).length,
      active_now: inQueue + inProgress,
    },
    latency: { inference: percentiles(inference), wall: percentiles(wall) },
    throughput: throughput(records, nowMs),
    cost: {
      estimated_cost_usd: cost,
      estimated_cost_usd_per_job: window.length ? cost / window.length : null,
      exec_seconds_in_window: execS,
      gpu_rate_usd_hr: GPU_RATE_USD_HR,
    },
    upstream: {
      queue: queueReading(mode, { inQueue, inProgress, workersRunning }),
      reconciler: reconcilerReading(mode),
    },
    window: windowSize,
    completed_in_window: window.length,
    window_started_at: completedMs.length
      ? new Date(Math.min(...completedMs)).toISOString()
      : null,
    window_ended_at: completedMs.length
      ? new Date(Math.max(...completedMs)).toISOString()
      : null,
    generated_at: new Date(nowMs).toISOString(),
  }
}

function unauthorized(request: Request) {
  const auth = request.headers.get('Authorization')
  if (!auth?.startsWith('Bearer ') || auth.length <= 'Bearer '.length) {
    return errorJson(
      401,
      'UNAUTHENTICATED',
      'Missing or invalid API key.',
      'Send Authorization: Bearer <secret>.',
    )
  }
  return null
}

export const handlers = [
  http.get('/health', () =>
    HttpResponse.json({ status: 'ok' }, { headers: withHeaders() }),
  ),

  http.post('/v1/jobs', async ({ request }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    const idemKey = request.headers.get('Idempotency-Key')
    const replayId = idemKey ? idempotencyKeys.get(idemKey) : undefined
    const replayJob = replayId ? jobs.get(replayId) : undefined
    if (idemKey && replayJob) {
      return HttpResponse.json(viewOf(replayJob), {
        status: 200,
        headers: withHeaders(),
      })
    }
    const body = (await request.json()) as {
      prompt: string
      width?: number
      height?: number
      num_inference_steps?: number
      guidance_scale?: number
      seed?: number
      output_format?: 'png' | 'jpeg'
    }
    const now = Date.now()
    const tokens = demoTokens(body.prompt)
    if (tokens.includes('shed-one')) {
      if (now - shedOneLastMs > 60_000) {
        shedOneLastMs = now
        return errorJson(
          429,
          'QUEUE_SATURATED',
          'The endpoint queue shed this submission.',
          'Retry after 8s.',
          { 'Retry-After': '8' },
        )
      }
    } else if (tokens.includes('shed')) {
      // sheds once per idempotency key: the first retry succeeds
      if (!idemKey || !shedKeys.has(idemKey)) {
        if (idemKey) shedKeys.add(idemKey)
        return errorJson(
          429,
          'QUEUE_SATURATED',
          'The endpoint queue is saturated.',
          'Retry after 22s.',
          { 'Retry-After': '22' },
        )
      }
    }
    const scenario: Scenario =
      tokens.includes('mixed') ? 'mixed'
      : tokens.includes('blocked') ? 'blocked'
      : tokens.includes('oom') ? 'oom'
      : tokens.includes('cold') ? 'cold'
      : tokens.includes('hold') ? 'hold'
      : 'ok'
    const burst = nextBurstIndex(now)
    const seed = body.seed ?? null
    if (burst === 0) burstFirstSeed = seed
    const sameSeedBurst = burst > 0 && seed !== null && seed === burstFirstSeed
    const job: MockJob = {
      id: crypto.randomUUID(),
      prompt: body.prompt,
      width: body.width ?? 1024,
      height: body.height ?? 1024,
      steps: body.num_inference_steps ?? 28,
      guidance: body.guidance_scale ?? 3.5,
      seed,
      format: body.output_format ?? 'png',
      createdAtMs: now,
      scenario,
      cancelledAtMs: null,
      corr: correlationId(),
      burst,
      sameSeedBurst,
    }
    jobs.set(job.id, job)
    if (idemKey) idempotencyKeys.set(idemKey, job.id)
    // 'demo:drop-first': the create lands but the response is lost once per
    // key — the client's key-reusing retry then hits the replay path above
    if (tokens.includes('drop-first') && idemKey && !droppedKeys.has(idemKey)) {
      droppedKeys.add(idemKey)
      return errorJson(
        502,
        'UPSTREAM_RESET',
        'The gateway accepted the job but the response was lost.',
        'Retry with the same Idempotency-Key to recover the job.',
      )
    }
    return HttpResponse.json(
      {
        job_id: job.id,
        status: 'QUEUED',
        created_at: new Date(job.createdAtMs).toISOString(),
      },
      { status: 202, headers: withHeaders() },
    )
  }),

  http.get('/v1/jobs/:jobId/image', async ({ request, params }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    const id = params.jobId as string
    const job = jobs.get(id)
    const summary = job ? null : staticSummaries().find((s) => s.job_id === id)
    if (!job && !summary) {
      return errorJson(404, 'JOB_NOT_FOUND', `No job with id ${id}.`)
    }
    // seed-keyed variants (scripts/make-seed-variants.mjs): same seed = same
    // bytes, different seed (mod 6) = visibly different image
    const seed = job ? (job.seed ?? 424242) : summary!.seed ?? 424242
    const variant = seed % 6
    const file = variant === 0 ? '/mock/sample.png' : `/mock/sample-${variant}.png`
    const res = await fetch(file)
    const bytes = await res.arrayBuffer()
    return new HttpResponse(bytes, {
      headers: withHeaders({ 'Content-Type': 'image/png' }),
    })
  }),

  http.get('/v1/jobs/:jobId', async ({ request, params }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    await ensurePreviewFrames()
    const id = params.jobId as string
    const job = jobs.get(id)
    if (job) return HttpResponse.json(viewOf(job), { headers: withHeaders() })
    const summary = staticSummaries().find((s) => s.job_id === id)
    if (summary)
      return HttpResponse.json(staticView(summary), { headers: withHeaders() })
    return errorJson(404, 'JOB_NOT_FOUND', `No job with id ${id}.`)
  }),

  http.get('/v1/jobs', ({ request }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    const dynamic = [...jobs.values()]
      .map((job) => ({ job, view: viewOf(job) }))
      .filter(({ view }) => view.status === 'COMPLETED')
      .map(({ job, view }): JobSummary => ({
        job_id: job.id,
        status: 'COMPLETED',
        prompt: job.prompt,
        width: job.width,
        height: job.height,
        num_inference_steps: job.steps,
        guidance_scale: job.guidance,
        output_format: job.format,
        seed: view.result!.seed,
        thumbhash: SAMPLE_THUMBHASH,
        image_url: `/v1/jobs/${job.id}/image`,
        model_version: MODEL_VERSION,
        inference_seconds: inferenceSeconds(job),
        error_code: null,
        created_at: view.created_at,
        completed_at: view.completed_at,
      }))
      .sort((a, b) => (a.created_at < b.created_at ? 1 : -1))
    return HttpResponse.json(
      { jobs: [...dynamic, ...staticSummaries()] },
      { headers: withHeaders() },
    )
  }),

  http.get('/v1/metrics', ({ request }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    return HttpResponse.json(metricsSnapshot(), { headers: withHeaders() })
  }),

  http.post('/v1/jobs/:jobId/cancel', ({ request, params }) => {
    const denied = unauthorized(request)
    if (denied) return denied
    const job = jobs.get(params.jobId as string)
    if (!job) {
      return errorJson(404, 'JOB_NOT_FOUND', `No job with id ${String(params.jobId)}.`)
    }
    const view = viewOf(job)
    if (view.status === 'QUEUED' || view.status === 'IN_PROGRESS') {
      job.cancelledAtMs = Date.now()
    }
    return HttpResponse.json(viewOf(job), { headers: withHeaders() })
  }),
]
