"""ThumbHash encoder, ported from the reference implementation.

Port of `rgbaToThumbHash` from evanw/thumbhash (js/thumbhash.js). PyPI's
`thumbhash` package was considered and rejected: last released 2023-03,
untyped, unverified. The algorithm is ~80 lines and frozen, so a first-party
port under mypy strict is cheaper than trusting it. Verified against vectors
generated by running the reference JavaScript (tests/unit/test_thumbhash.py).
"""

from __future__ import annotations

import math

MAX_DIMENSION = 100


def _round(value: float) -> int:
    """Round half up, matching JavaScript's `Math.round`.

    Python's built-in `round` is banker's rounding; using it here would
    diverge from the reference on exact halves.

    Args:
        value: A non-negative quantized coefficient.

    Returns:
        The nearest integer, halves rounded toward positive infinity.
    """
    return math.floor(value + 0.5)


def _averages(
    width: int, height: int, rgba: bytes
) -> tuple[float, float, float, float]:
    """Return the alpha-weighted average color and the alpha total.

    Args:
        width: Image width in pixels.
        height: Image height in pixels.
        rgba: Row-major RGBA bytes, not premultiplied.

    Returns:
        `(avg_r, avg_g, avg_b, avg_a)` where the RGB terms are in [0, 1] and
        `avg_a` is the sum of per-pixel alpha in [0, width*height].
    """
    avg_r = avg_g = avg_b = avg_a = 0.0
    for i in range(width * height):
        j = i * 4
        alpha = rgba[j + 3] / 255
        avg_r += alpha / 255 * rgba[j]
        avg_g += alpha / 255 * rgba[j + 1]
        avg_b += alpha / 255 * rgba[j + 2]
        avg_a += alpha
    if avg_a:
        avg_r /= avg_a
        avg_g /= avg_a
        avg_b /= avg_a
    return avg_r, avg_g, avg_b, avg_a


def _to_lpqa(
    width: int, height: int, rgba: bytes, averages: tuple[float, float, float, float]
) -> tuple[list[float], list[float], list[float], list[float]]:
    """Convert RGBA to LPQA channels, composited atop the average color.

    Args:
        width: Image width in pixels.
        height: Image height in pixels.
        rgba: Row-major RGBA bytes, not premultiplied.
        averages: The `_averages` result for this image.

    Returns:
        Luminance, yellow-blue, red-green and alpha channels, one float per
        pixel each.
    """
    avg_r, avg_g, avg_b, _ = averages
    lum: list[float] = []
    yb: list[float] = []
    rg: list[float] = []
    alpha_channel: list[float] = []
    for i in range(width * height):
        j = i * 4
        alpha = rgba[j + 3] / 255
        r = avg_r * (1 - alpha) + alpha / 255 * rgba[j]
        g = avg_g * (1 - alpha) + alpha / 255 * rgba[j + 1]
        b = avg_b * (1 - alpha) + alpha / 255 * rgba[j + 2]
        lum.append((r + g + b) / 3)
        yb.append((r + g) / 2 - b)
        rg.append(r - g)
        alpha_channel.append(alpha)
    return lum, yb, rg, alpha_channel


def _encode_channel(
    channel: list[float], nx: int, ny: int, width: int, height: int
) -> tuple[float, list[float], float]:
    """DCT-encode one channel into a DC term and normalized AC terms.

    Args:
        channel: One float per pixel, row-major.
        nx: Horizontal frequency budget.
        ny: Vertical frequency budget.
        width: Image width in pixels.
        height: Image height in pixels.

    Returns:
        `(dc, ac, scale)`: the constant term, the AC terms normalized into
        [0, 1], and the scale that normalized them.
    """
    dc = 0.0
    ac: list[float] = []
    scale = 0.0
    for cy in range(ny):
        cx = 0
        while cx * ny < nx * (ny - cy):
            fx = [math.cos(math.pi / width * cx * (x + 0.5)) for x in range(width)]
            f = 0.0
            for y in range(height):
                fy = math.cos(math.pi / height * cy * (y + 0.5))
                row = y * width
                for x in range(width):
                    f += channel[row + x] * fx[x] * fy
            f /= width * height
            if cx or cy:
                ac.append(f)
                scale = max(scale, abs(f))
            else:
                dc = f
            cx += 1
    if scale:
        ac = [0.5 + 0.5 / scale * f for f in ac]
    return dc, ac, scale


def rgba_to_thumbhash(width: int, height: int, rgba: bytes) -> bytes:
    """Encode an RGBA image as a ThumbHash.

    Args:
        width: Image width, at most 100.
        height: Image height, at most 100.
        rgba: Row-major RGBA bytes, `width * height * 4` of them, RGB not
            premultiplied by alpha.

    Returns:
        The hash bytes, 21-25 for typical opaque images.

    Raises:
        ValueError: A dimension exceeds 100, or `rgba` has the wrong length.
    """
    if width > MAX_DIMENSION or height > MAX_DIMENSION:
        msg = f"{width}x{height} doesn't fit in 100x100"
        raise ValueError(msg)
    if len(rgba) != width * height * 4:
        msg = f"expected {width * height * 4} RGBA bytes, got {len(rgba)}"
        raise ValueError(msg)

    averages = _averages(width, height, rgba)
    has_alpha = averages[3] < width * height
    lum, yb, rg, alpha_channel = _to_lpqa(width, height, rgba, averages)

    l_limit = 5 if has_alpha else 7  # fewer luminance bits leave room for alpha
    lx = max(1, _round(l_limit * width / max(width, height)))
    ly = max(1, _round(l_limit * height / max(width, height)))
    l_dc, l_ac, l_scale = _encode_channel(lum, max(3, lx), max(3, ly), width, height)
    p_dc, p_ac, p_scale = _encode_channel(yb, 3, 3, width, height)
    q_dc, q_ac, q_scale = _encode_channel(rg, 3, 3, width, height)

    is_landscape = width > height
    header24 = (
        _round(63 * l_dc)
        | (_round(31.5 + 31.5 * p_dc) << 6)
        | (_round(31.5 + 31.5 * q_dc) << 12)
        | (_round(31 * l_scale) << 18)
        | (int(has_alpha) << 23)
    )
    header16 = (
        (ly if is_landscape else lx)
        | (_round(63 * p_scale) << 3)
        | (_round(63 * q_scale) << 9)
        | (int(is_landscape) << 15)
    )
    hash_bytes = bytearray(
        [
            header24 & 255,
            (header24 >> 8) & 255,
            header24 >> 16,
            header16 & 255,
            header16 >> 8,
        ]
    )
    channels = [l_ac, p_ac, q_ac]
    if has_alpha:
        a_dc, a_ac, a_scale = _encode_channel(alpha_channel, 5, 5, width, height)
        hash_bytes.append(_round(15 * a_dc) | (_round(15 * a_scale) << 4))
        channels.append(a_ac)

    ac_start = len(hash_bytes)
    ac_index = 0
    for ac in channels:
        for f in ac:
            position = ac_start + (ac_index >> 1)
            if position >= len(hash_bytes):
                hash_bytes.append(0)
            hash_bytes[position] |= _round(15 * f) << ((ac_index & 1) << 2)
            ac_index += 1
    return bytes(hash_bytes)


def thumbhash_to_average_rgba(hash_bytes: bytes) -> tuple[float, float, float, float]:
    """Extract the average color from a ThumbHash.

    Port of the reference `thumbHashToAverageRGBA`; used by the tests to
    cross-check bit packing against the encoder.

    Args:
        hash_bytes: The hash produced by `rgba_to_thumbhash`.

    Returns:
        `(r, g, b, a)`, each in [0, 1], RGB not premultiplied.
    """
    header = hash_bytes[0] | (hash_bytes[1] << 8) | (hash_bytes[2] << 16)
    lum = (header & 63) / 63
    yb = ((header >> 6) & 63) / 31.5 - 1
    rg = ((header >> 12) & 63) / 31.5 - 1
    has_alpha = header >> 23 != 0
    a = (hash_bytes[5] & 15) / 15 if has_alpha else 1.0
    b = lum - 2 / 3 * yb
    r = (3 * lum - b + rg) / 2
    g = r - rg

    def clamp(value: float) -> float:
        return max(0.0, min(1.0, value))

    return clamp(r), clamp(g), clamp(b), a
